-- Get lineage with size in MB
WITH lineage_objects AS (
    SELECT 
        SOURCE_OBJECT_NAME,
        SOURCE_OBJECT_DOMAIN,
        DISTANCE,
        SPLIT_PART(SOURCE_OBJECT_NAME, '.', 1) AS DB_NAME,
        SPLIT_PART(SOURCE_OBJECT_NAME, '.', 2) AS SCHEMA_NAME,
        SPLIT_PART(SOURCE_OBJECT_NAME, '.', 3) AS OBJ_NAME
    FROM TABLE(
        SNOWFLAKE.CORE.GET_LINEAGE(
            'DATABASE.SCHEMA.TABLE_NAME',
            'TABLE',
            'UPSTREAM',
            5
        )
    )
    WHERE SOURCE_OBJECT_NAME IS NOT NULL
)
SELECT 
    l.SOURCE_OBJECT_NAME,
    l.SOURCE_OBJECT_DOMAIN,
    l.DISTANCE,
    t.ROW_COUNT,
    t.BYTES,
    ROUND(t.BYTES / 1024 / 1024, 2) AS SIZE_MB
FROM lineage_objects l
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.TABLES t
    ON UPPER(l.DB_NAME) = UPPER(t.TABLE_CATALOG)
    AND UPPER(l.SCHEMA_NAME) = UPPER(t.TABLE_SCHEMA)
    AND UPPER(l.OBJ_NAME) = UPPER(t.TABLE_NAME)
    AND t.DELETED IS NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY l.SOURCE_OBJECT_NAME ORDER BY t.LAST_ALTERED DESC) = 1
ORDER BY SIZE_MB DESC NULLS LAST;

-- Total size in MB
SELECT 
    COUNT(DISTINCT l.SOURCE_OBJECT_NAME) AS OBJECT_COUNT,
    SUM(t.ROW_COUNT) AS TOTAL_ROWS,
    ROUND(SUM(t.BYTES) / 1024 / 1024, 2) AS TOTAL_SIZE_MB
FROM TABLE(
    SNOWFLAKE.CORE.GET_LINEAGE('DATABASE.SCHEMA.TABLE_NAME', 'TABLE', 'UPSTREAM', 5)
) l
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.TABLES t
    ON l.SOURCE_OBJECT_NAME = CONCAT(t.TABLE_CATALOG, '.', t.TABLE_SCHEMA, '.', t.TABLE_NAME)
    AND t.DELETED IS NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY l.SOURCE_OBJECT_NAME ORDER BY t.LAST_ALTERED DESC) = 1;
